#!/usr/bin/env node

const fs = require('fs');
const path = require('path');

const Lexer     = require('./Lexer/lexer');
const Parser    = require('./Parser/parser');
const Evaluator = require('./Evaluator/evaluate');
const { instalar, remover, listar, procurar, ajuda, whoami } = require('./Instalador/instalador');
const { publicar, salvarToken } = require('./Instalador/publicador');

const args = process.argv.slice(2);
const comando = args[0];

if (comando === 'instalar') {
    instalar(args[1]);
} else if (comando === 'remover') {
    remover(args[1]);
} else if (comando === 'listar') {
    listar();
} else if (comando === 'procurar') {
    procurar(args[1]);
} else if (comando === 'publicar') {
    publicar();
} else if (comando === 'login') {
    if (!args[1]) {
        console.error('❌ Uso: mambas login <token>');
        process.exit(1);
    }
    salvarToken(args[1]);
} else if (comando === 'ajuda' || comando === '--ajuda' || comando === '-a') {
    ajuda();
} else if (comando === 'whoami') {
    whoami();
} else if (comando === '--versao' || comando === '-v') {
    const pkg = require('./package.json');
    console.log(`MambaScript v${pkg.version}`);
    process.exit(0);
} else if (comando === 'init') {
    const { init } = require('./Instalador/instalador');
    init();
} else if (!comando) {
    ajuda();
} else {
    const filename = comando;
    const fullPath = path.isAbsolute(filename)
        ? filename
        : path.join(process.cwd(), filename);

    if (!fs.existsSync(fullPath)) {
        console.error(`Erro: Arquivo não encontrado: ${filename}`);
        process.exit(1);
    }

    const code = fs.readFileSync(fullPath, 'utf-8');

    (async () => {
        try {
            const lexer     = new Lexer(code);
            const tokens    = lexer.tokenize();
            const parser    = new Parser(tokens);
            const ast       = parser.parse();
            const evaluator = new Evaluator(fullPath);
            await evaluator.execute(ast);
        } catch (error) {
            console.error('❌ Erro MambaScript:', error.message);
            process.exit(1);
        }
    })();
}
